name: 基金金价监控日报

on:
  schedule:
    # 计划任务：UTC 02:00 = 北京时间 10:00
    # 1,3,5 代表 周一、三、五
    - cron: '0 2 * * 1,3,5'
  
  # 允许手动点击按钮运行 (方便立刻测试)
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: 1. 拉取代码
      uses: actions/checkout@v3
      
    - name: 2. 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: 3. 安装依赖
      run: |
        pip install requests
        
    - name: 4. 运行脚本
      env:
        # 这里就是把 Secrets 里的密码传给 Python 里的 os.environ
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASS: ${{ secrets.SENDER_PASS }}
      # 注意：你的代码在 src 目录下
      run: python src/get_found_rate.py
